---
- hosts: mywebserversvers
  become: yes
  gather_fact: yes
  tasks:
  - name: in this tasks , i want to install apache2 webservers on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family== "Debian"
  - name: in this tasks, i want to start apache2 webservers on ubuntu
    service:
      name: apache2
      state: started
    when: ansible_os_family== "Debian"
  - name: in this tasks, i want to install httpd webservers on RedHat
    dnf: 
     name: httpd 
     state: present
    when: ansible_os_family== "RedHat"
  - name: in this tasks, i want to start httpd webservers on RedHat
    service: 
     name: httpd
     state: started
    when: ansible_os_family==  "RedHat"